ubicaciones = ["Cuba", "Londres", "Madrid", "Paris", "Chile"]
print("Ubicaciones original:")
print(ubicaciones)
print("Ubicaciones con sorted:")
print(sorted(ubicaciones))
print("Ubicaciones original:")
print(ubicaciones)
print("Ubicaciones con sorted y reverse:")
print(sorted(ubicaciones,reverse=True))
print("Ubicaciones original:")
print(ubicaciones)
print("Ubicaciones con reverse:")
ubicaciones.reverse()
print(ubicaciones)
ubicaciones.reverse()
print("Ubicaciones original:")
print(ubicaciones)
ubicaciones.sort()
print("Ubicaciones con sort:")
print(ubicaciones)
ubicaciones.sort(reverse=True)
print("Ubicaciones con sort inverso:")
print(ubicaciones)